#!/bin/bash
set -e -x

pushd $HOME

rm -f .vimrc .zshrc .gitconfig

ln -s dotfiles/gitconfig .gitconfig
ln -s dotfiles/vimrc .vimrc
ln -s dotfiles/zshrc .zshrc

git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh

chsh -s /bin/zsh

vim -c "BundleInstall" -cq -cq -e

popd
