#!/bin/bash
set -e

if [ ! -f /bin/zsh ]; then
  sudo apt-get update
  sudo apt-get install -y vim zsh htop screen git
fi

pushd $HOME

rm -f .vimrc .zshrc .gitconfig .gemrc

ln -s dotfiles/gemrc .gemrc
ln -s dotfiles/gitconfig .gitconfig
ln -s dotfiles/vimrc .vimrc
ln -s dotfiles/zshrc .zshrc

if [ ! -d ~/.vim/bundle/vundle ]; then
  git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
fi

if [ ! -d ~/.oh-my-zsh ]; then
  git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
fi

chsh -s /bin/zsh

vim -c "BundleInstall" -cq -cq -e

popd
